syntax = "proto3";

package qodex.threadui.ipc.ui_to_qodex;

import "common.proto";

service UiToQodex {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc TestPing(TestPingRequest) returns (TestPingResponse);
}

message LoginRequest {
  string token = 1;
}

message LoginResponse {
  qodex.threadui.ipc.common.ResultStatus status = 1;
  string message = 2;
}

message TestPingRequest {
  int64 value = 1;
}

message TestPingResponse {
  qodex.threadui.ipc.common.ResultStatus status = 1;
  string message = 2;
}
