syntax = "proto3";

package qodex.threadui.ipc.ui_to_qodex;

import "common.proto";

service UiToQodex {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc SendUserInput(SendUserInputRequest) returns (SendUserInputResponse);
  rpc ResolveLink(ResolveLinkRequest) returns (ResolveLinkResponse);
}

message LoginRequest {
  string token = 1;
}

message LoginResponse {
  qodex.threadui.ipc.common.ResultStatus status = 1;
  string message = 2;
}

message SendUserInputRequest {
  string text = 1;
}

message SendUserInputResponse {
  qodex.threadui.ipc.common.ResultStatus status = 1;
  string message = 2;
}

message ResolveLinkRequest {
  string href = 1;
}

message ResolveLinkResponse {
  qodex.threadui.ipc.common.ResultStatus status = 1;
  string message = 2;
  qodex.threadui.ipc.common.ResolvedLink resolved_link = 3;
}
